import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/Sidebar";
import { Box } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Box display={"flex"}>
          <SideBar />
          <Box>
            <Box
                  sx={{
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                    flexDirection: "column",
                    height: "100vh",
                    width: "100%",
                    px: 2,
                    mx: "auto",
                  }}
                >
                  {/*the subsa logo part*/}
                  <Box
                    sx={{
                      alignItems: "center",
                      width: "100%",
                      px: 2,
                    }}
                  >
                    The Subasa
                  </Box>
            
                  {/*the model selection part*/}
                  
                </Box>
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
